
about :

  name : "wRemoteRequire"
  description : " "
  version : "0.3.13"
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wRemoteRequire.git
  bugs : https://github.com/Wandalen/wRemoteRequire/issues

step :

  export.proto :
    inherit : export
    export : path::proto
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      export : 1
      tar : 1
    steps :
      - build::debug.raw
      - step::export.proto

